require "user.launch"
require "user.options"
require "user.keymaps"
require "user.autocmds"
spec "user.colorscheme"
spec "user.devicons"
spec "user.navic"
spec "user.breadcrumbs"
spec "user.treesitter"
spec "user.mason"
spec "user.schemastore"
spec "user.lspconfig"
spec "user.cmp"
spec "user.telescope"
spec "user.none-ls"
spec "user.project"
spec "user.whichkey"
spec "user.nvimtree"
spec "user.comment"
spec "user.lualine"
spec "user.harpoon"
spec "user.extras.neoscroll"
spec "user.illuminate"
spec "user.extras.oil"
spec "user.extras.ufo"
spec "user.extras.cellular-automaton"
spec "user.extras.eyeliner"
spec "user.neotest"
spec "user.extras.neotab"
spec "user.gitsigns"
spec "user.autopairs"
spec "user.extras.gitlinker"
spec "user.snacks"
spec "user.extras.tabby"
spec "user.indentline"
spec "user.toggleterm"
spec "user.extras.fidget"
spec "user.extras.bqf"
spec "user.extras.colorizer"
spec "user.extras.dressing"
spec "user.extras.modicator"
spec "user.extras.noice"
spec "user.extras.compiler"
spec "user.obsidian"
spec "user.debugger" 

-- Uninstalled Plugins
-- spec "user.extras.lab"
-- spec "user.neogit"
-- spec "user.extras.tabnine"
-- spec "user.extras.navbuddy"
-- spec "user.extras.hardtime"
-- spec "user.alpha"
-- spec "user.legendary"
-- spec "user.extras.copilot"
-- spec "user.extras.codecompanion"
-- Leave this at the end of the file
require ("user.lazy")
